packageExtensions:
  "@node-rs/helper@*":
    dependencies:
      # For dev env mac
      "@swc/core-darwin": "*"
      # For github action
      "@swc/core-linux": "*"
      "@swc/core-linux-musl": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.2.cjs
